import UserInfoService from "../../service/UserInfoService.js";

export default async function seedUserInfo() {
  const userInfos = [
    {
      firstName: "Hồng",
      lastName: "Nguyễn",
      gender: "Nữ",
      birthday: "2000-05-15",
      email: "hongnguyen@resident.myhome.com",
      phone: "0912345678",
      city: "Hà Nội",
      district: "Ba Đình",
      subdistrict: "Quán Thánh",
      address: "Số 123, Ngách 45, Ngõ 67, Quán Thánh, Ba Đình, Hà Nội",
      ApartmentId: 1,
      account: true,
    },
    {
      firstName: "Trung",
      lastName: "Phạm",
      gender: "Nam",
      birthday: "1995-09-20",
      email: "trungpham@staff.myhome.com",
      phone: "0987654321",
      city: "Đà Nẵng",
      district: "Hải Châu",
      subdistrict: "Thạch Thang",
      address: "Số 456, Ngõ 78, Thạch Thang, Hải Châu, Đà Nẵng",
      ApartmentId: 2,
      account: true,
    },
    {
      firstName: "Lan",
      lastName: "Trần",
      gender: "Nữ",
      birthday: "2005-02-10",
      email: "lantran@admin.myhome.com",
      phone: "0978123456",
      city: "Hồ Chí Minh",
      district: "Quận 5",
      subdistrict: "Phường 10",
      address: "Số 789, Ngõ 90, Phường 10, Quận 5, Hồ Chí Minh",
      ApartmentId: 3,
      account: false,
    },
    {
      firstName: "Nam",
      lastName: "Ngô",
      gender: "Nam",
      birthday: "1998-07-08",
      email: "namngo@resident.myhome.com",
      phone: "0922334455",
      city: "Hà Nội",
      district: "Hoàng Mai",
      subdistrict: "Mai Động",
      address: "Số 234, Ngõ 56, Mai Động, Hoàng Mai, Hà Nội",
      ApartmentId: 4,
      account: true,
    },
    {
      firstName: "Thu",
      lastName: "Trần",
      gender: "Nữ",
      birthday: "1993-12-25",
      email: "thutran@staff.myhome.com",
      phone: "0966888999",
      city: "Hồ Chí Minh",
      district: "Quận 7",
      subdistrict: "Phường Tân Phong",
      address: "Số 567, Ngõ 78, Phường Tân Phong, Quận 7, Hồ Chí Minh",
      ApartmentId: 5,
      account: true,
    },
    {
      firstName: "Quang",
      lastName: "Lê",
      gender: "Nam",
      birthday: "2007-03-18",
      email: "quangle@admin.myhome.com",
      phone: "0911223344",
      city: "Đà Nẵng",
      district: "Quận Liên Chiểu",
      subdistrict: "Phường Thanh Khê Đông",
      address:
        "Số 789, Ngõ 90, Phường Thanh Khê Đông, Quận Liên Chiểu, Đà Nẵng",
      ApartmentId: 6,
      account: false,
    },
    {
      firstName: "Hạnh",
      lastName: "Nguyễn",
      gender: "Nữ",
      birthday: "1999-08-30",
      email: "hanhnguyen@resident.myhome.com",
      phone: "0987654321",
      city: "Hà Nội",
      district: "Hai Bà Trưng",
      subdistrict: "Lê Đại Hành",
      address: "Số 123, Ngõ 45, Lê Đại Hành, Hai Bà Trưng, Hà Nội",
      ApartmentId: 7,
      account: true,
    },
    {
      firstName: "Đức",
      lastName: "Phạm",
      gender: "Nam",
      birthday: "2001-04-22",
      email: "ducpham@staff.myhome.com",
      phone: "0978123456",
      city: "Hồ Chí Minh",
      district: "Quận 1",
      subdistrict: "Bến Thành",
      address: "Số 456, Ngõ 78, Bến Thành, Quận 1, Hồ Chí Minh",
      ApartmentId: 8,
      account: true,
    },
    {
      firstName: "Linh",
      lastName: "Vũ",
      gender: "Nữ",
      birthday: "2006-11-12",
      email: "linhvuc@admin.myhome.com",
      phone: "0922334455",
      city: "Đà Nẵng",
      district: "Quận Sơn Trà",
      subdistrict: "Phường Mân Thái",
      address: "Số 789, Ngõ 90, Phường Mân Thái, Quận Sơn Trà, Đà Nẵng",
      ApartmentId: 9,
      account: false,
    },
    {
      firstName: "Minh",
      lastName: "Nguyễn",
      gender: "Nam",
      birthday: "1997-06-05",
      email: "minhnguyen@resident.myhome.com",
      phone: "0966888999",
      city: "Hồ Chí Minh",
      district: "Quận 2",
      subdistrict: "Thảo Điền",
      address: "Số 123, Ngõ 45, Thảo Điền, Quận 2, Hồ Chí Minh",
      ApartmentId: 10,
      account: true,
    },
    {
      firstName: "Hà",
      lastName: "Trần",
      gender: "Nữ",
      birthday: "2000-01-20",
      email: "hatran@staff.myhome.com",
      phone: "0911223344",
      city: "Hà Nội",
      district: "Ba Đình",
      subdistrict: "Trúc Bạch",
      address: "Số 456, Ngõ 78, Trúc Bạch, Ba Đình, Hà Nội",
      ApartmentId: 11,
      account: false,
    },
    {
      firstName: "Thành",
      lastName: "Lê",
      gender: "Nam",
      birthday: "1998-03-18",
      email: "thanhle@admin.myhome.com",
      phone: "0912345678",
      city: "Đà Nẵng",
      district: "Quận Hải Châu",
      subdistrict: "Phường Nam Dương",
      address: "Số 789, Ngõ 90, Phường Nam Dương, Quận Hải Châu, Đà Nẵng",
      ApartmentId: 12,
      account: true,
    },
    {
      firstName: "Trang",
      lastName: "Ngô",
      gender: "Nữ",
      birthday: "2005-09-10",
      email: "trangngo@resident.myhome.com",
      phone: "0987654321",
      city: "Hồ Chí Minh",
      district: "Quận 3",
      subdistrict: "Phường 6",
      address: "Số 123, Ngõ 45, Phường 6, Quận 3, Hồ Chí Minh",
      ApartmentId: 13,
      account: true,
    },
    {
      firstName: "Tuấn",
      lastName: "Phạm",
      gender: "Nam",
      birthday: "1994-12-25",
      email: "tuanpham@staff.myhome.com",
      phone: "0978123456",
      city: "Hà Nội",
      district: "Hoàn Kiếm",
      subdistrict: "Phan Chu Trinh",
      address: "Số 456, Ngõ 78, Phan Chu Trinh, Hoàn Kiếm, Hà Nội",
      ApartmentId: 14,
      account: false,
    },
    {
      firstName: "Yến",
      lastName: "Lê",
      gender: "Nữ",
      birthday: "1999-08-30",
      email: "yenle@admin.myhome.com",
      phone: "0922334455",
      city: "Đà Nẵng",
      district: "Quận Sơn Trà",
      subdistrict: "Phường Thọ Quang",
      address: "Số 789, Ngõ 90, Phường Thọ Quang, Quận Sơn Trà, Đà Nẵng",
      ApartmentId: 15,
      account: true,
    },
    {
      firstName: "Dũng",
      lastName: "Nguyễn",
      gender: "Nam",
      birthday: "1996-05-15",
      email: "dungnguyen@resident.myhome.com",
      phone: "0966888999",
      city: "Hồ Chí Minh",
      district: "Quận 4",
      subdistrict: "Phường 7",
      address: "Số 123, Ngõ 45, Phường 7, Quận 4, Hồ Chí Minh",
      ApartmentId: 16,
      account: true,
    },
    {
      firstName: "Hương",
      lastName: "Trần",
      gender: "Nữ",
      birthday: "2001-02-10",
      email: "huongtran@staff.myhome.com",
      phone: "0911223344",
      city: "Hà Nội",
      district: "Hoàng Mai",
      subdistrict: "Lĩnh Nam",
      address: "Số 456, Ngõ 78, Lĩnh Nam, Hoàng Mai, Hà Nội",
      ApartmentId: 17,
      account: false,
    },
    {
      firstName: "Việt",
      lastName: "Phạm",
      gender: "Nam",
      birthday: "2003-11-12",
      email: "vietpham@admin.myhome.com",
      phone: "0912345678",
      city: "Đà Nẵng",
      district: "Quận Liên Chiểu",
      subdistrict: "Phường Thanh Khê Đông",
      address:
        "Số 789, Ngõ 90, Phường Thanh Khê Đông, Quận Liên Chiểu, Đà Nẵng",
      ApartmentId: 18,
      account: true,
    },
    {
      firstName: "Hà",
      lastName: "Lê",
      gender: "Nữ",
      birthday: "1997-06-05",
      email: "hale@resident.myhome.com",
      phone: "0987654321",
      city: "Hồ Chí Minh",
      district: "Quận 1",
      subdistrict: "Bến Thành",
      address: "Số 123, Ngõ 45, Bến Thành, Quận 1, Hồ Chí Minh",
      ApartmentId: 19,
      account: true,
    },
    {
      firstName: "Khải",
      lastName: "Ngô",
      gender: "Nam",
      birthday: "2002-01-20",
      email: "khai.ngo@staff.myhome.com",
      phone: "0978123456",
      city: "Hà Nội",
      district: "Ba Đình",
      subdistrict: "Trúc Bạch",
      address: "Số 456, Ngõ 78, Trúc Bạch, Ba Đình, Hà Nội",
      ApartmentId: 20,
      account: false,
    },
  ];

  for (const userInfo of userInfos) {
    await UserInfoService.createUserInfoNew(userInfo);
  }
}
