import UserInfoService from "../../service/UserInfoService.js";

export default async function seedUserInfo() {
  const userInfos = [
    {
      firstName: "Hồng",
      lastName: "Nguyễn",
      gender: "Nữ",
      birthday: "2000-05-15",
      email: "hongnguyen@resident.myhome.com",
      phone: "0912345678",
      city: "Hà Nội",
      district: "Ba Đình",
      subdistrict: "Quán Thánh",
      address: "Số 123, Ngách 45, Ngõ 67, Quán Thánh, Ba Đình, Hà Nội",
      ApartmentId: null,
      account: true,
      joinDate: "2019-01-01",
      leaveDate: "2021-01-01",
    },
    {
      firstName: "Trung",
      lastName: "Phạm",
      gender: "Nam",
      birthday: "1995-09-20",
      email: "trungpham@staff.myhome.com",
      phone: "0987654321",
      city: "Đà Nẵng",
      district: "Hải Châu",
      subdistrict: "Thạch Thang",
      address: "Số 456, Ngõ 78, Thạch Thang, Hải Châu, Đà Nẵng",
      ApartmentId: 2,
      account: true,
      joinDate: "2018-01-01",
      leaveDate: null,
    },
    {
      firstName: "Lan",
      lastName: "Trần",
      gender: "Nữ",
      birthday: "2005-02-10",
      email: "lantran@admin.myhome.com",
      phone: "0978123456",
      city: "Hồ Chí Minh",
      district: "Quận 5",
      subdistrict: "Phường 10",
      address: "Số 789, Ngõ 90, Phường 10, Quận 5, Hồ Chí Minh",
      ApartmentId: null,
      account: false,
      joinDate: "2017-01-01",
      leaveDate: "2019-01-01",
    },
    {
      firstName: "Nam",
      lastName: "Ngô",
      gender: "Nam",
      birthday: "1998-07-08",
      email: "namngo@resident.myhome.com",
      phone: "0922334455",
      city: "Hà Nội",
      district: "Hoàng Mai",
      subdistrict: "Mai Động",
      address: "Số 234, Ngõ 56, Mai Động, Hoàng Mai, Hà Nội",
      ApartmentId: null,
      account: true,
      joinDate: "2016-01-01",
      leaveDate: "2018-01-01",
    },
    {
      firstName: "Thu",
      lastName: "Trần",
      gender: "Nữ",
      birthday: "1993-12-25",
      email: "thutran@staff.myhome.com",
      phone: "0966888999",
      city: "Hồ Chí Minh",
      district: "Quận 7",
      subdistrict: "Phường Tân Phong",
      address: "Số 567, Ngõ 78, Phường Tân Phong, Quận 7, Hồ Chí Minh",
      ApartmentId: 5,
      account: true,
      joinDate: "2015-01-01",
      leaveDate: null,
    },
    {
      firstName: "Quang",
      lastName: "Lê",
      gender: "Nam",
      birthday: "2007-03-18",
      email: "quangle@admin.myhome.com",
      phone: "0911223344",
      city: "Đà Nẵng",
      district: "Quận Liên Chiểu",
      subdistrict: "Phường Thanh Khê Đông",
      address:
        "Số 789, Ngõ 90, Phường Thanh Khê Đông, Quận Liên Chiểu, Đà Nẵng",
      ApartmentId: 6,
      account: false,
      joinDate: "2019-01-01",
      leaveDate: null,
    },
    {
      firstName: "Hạnh",
      lastName: "Nguyễn",
      gender: "Nữ",
      birthday: "1999-08-30",
      email: "hanhnguyen@resident.myhome.com",
      phone: "0987654321",
      city: "Hà Nội",
      district: "Hai Bà Trưng",
      subdistrict: "Lê Đại Hành",
      address: "Số 123, Ngõ 45, Lê Đại Hành, Hai Bà Trưng, Hà Nội",
      ApartmentId: 7,
      account: true,
      joinDate: "2020-01-01",
      leaveDate: null,
    },
    {
      firstName: "Đức",
      lastName: "Phạm",
      gender: "Nam",
      birthday: "2001-04-22",
      email: "ducpham@staff.myhome.com",
      phone: "0978123456",
      city: "Hồ Chí Minh",
      district: "Quận 1",
      subdistrict: "Bến Thành",
      address: "Số 456, Ngõ 78, Bến Thành, Quận 1, Hồ Chí Minh",
      ApartmentId: 8,
      account: true,
      joinDate: "2021-01-01",
      leaveDate: null,
    },
    {
      firstName: "Linh",
      lastName: "Vũ",
      gender: "Nữ",
      birthday: "2006-11-12",
      email: "linhvuc@admin.myhome.com",
      phone: "0922334455",
      city: "Đà Nẵng",
      district: "Quận Sơn Trà",
      subdistrict: "Phường Mân Thái",
      address: "Số 789, Ngõ 90, Phường Mân Thái, Quận Sơn Trà, Đà Nẵng",
      ApartmentId: 9,
      account: false,
      joinDate: "2019-01-01",
      leaveDate: null,
    },
    {
      firstName: "Minh",
      lastName: "Nguyễn",
      gender: "Nam",
      birthday: "1997-06-05",
      email: "minhnguyen@resident.myhome.com",
      phone: "0966888999",
      city: "Hồ Chí Minh",
      district: "Quận 2",
      subdistrict: "Thảo Điền",
      address: "Số 123, Ngõ 45, Thảo Điền, Quận 2, Hồ Chí Minh",
      ApartmentId: 10,
      account: true,
      joinDate: "2020-01-01",
      leaveDate: null,
    },
    {
      firstName: "Hà",
      lastName: "Trần",
      gender: "Nữ",
      birthday: "2000-01-20",
      email: "hatran@staff.myhome.com",
      phone: "0911223344",
      city: "Hà Nội",
      district: "Ba Đình",
      subdistrict: "Trúc Bạch",
      address: "Số 456, Ngõ 78, Trúc Bạch, Ba Đình, Hà Nội",
      ApartmentId: null,
      account: false,
      joinDate: "2018-01-01",
      leaveDate: "2020-01-01",
    },
    {
      firstName: "Thành",
      lastName: "Lê",
      gender: "Nam",
      birthday: "1998-03-18",
      email: "thanhle@admin.myhome.com",
      phone: "0912345678",
      city: "Đà Nẵng",
      district: "Quận Hải Châu",
      subdistrict: "Phường Nam Dương",
      address: "Số 789, Ngõ 90, Phường Nam Dương, Quận Hải Châu, Đà Nẵng",
      ApartmentId: 12,
      account: true,
      joinDate: "2019-01-01",
      leaveDate: null,
    },
    {
      firstName: "Trang",
      lastName: "Ngô",
      gender: "Nữ",
      birthday: "2005-09-10",
      email: "trangngo@resident.myhome.com",
      phone: "0987654321",
      city: "Hồ Chí Minh",
      district: "Quận 3",
      subdistrict: "Phường 6",
      address: "Số 123, Ngõ 45, Phường 6, Quận 3, Hồ Chí Minh",
      ApartmentId: 13,
      account: true,
      joinDate: "2017-01-01",
      leaveDate: null,
    },
    {
      firstName: "Tuấn",
      lastName: "Phạm",
      gender: "Nam",
      birthday: "1994-12-25",
      email: "tuanpham@staff.myhome.com",
      phone: "0978123456",
      city: "Hà Nội",
      district: "Hoàn Kiếm",
      subdistrict: "Phan Chu Trình",
      address: "Số 456, Ngõ 78, Phan Chu Trình, Hoàn Kiếm, Hà Nội",
      ApartmentId: 14,
      account: false,
      joinDate: "2018-01-01",
      leaveDate: null,
    },
    {
      firstName: "Yến",
      lastName: "Lê",
      gender: "Nữ",
      birthday: "1999-08-30",
      email: "yenle@admin.myhome.com",
      phone: "0922334455",
      city: "Đà Nẵng",
      district: "Quận Sơn Trà",
      subdistrict: "Phường Thọ Quang",
      address: "Số 789, Ngõ 90, Phường Thọ Quang, Quận Sơn Trà, Đà Nẵng",
      ApartmentId: 15,
      account: true,
      joinDate: "2019-01-01",
      leaveDate: null,
    },
    {
      firstName: "Dũng",
      lastName: "Nguyễn",
      gender: "Nam",
      birthday: "1996-05-15",
      email: "dungnguyen@resident.myhome.com",
      phone: "0966888999",
      city: "Hồ Chí Minh",
      district: "Quận 4",
      subdistrict: "Phường 7",
      address: "Số 123, Ngõ 45, Phường 7, Quận 4, Hồ Chí Minh",
      ApartmentId: 16,
      account: true,
      joinDate: "2018-01-01",
      leaveDate: null,
    },
    {
      firstName: "Hương",
      lastName: "Trần",
      gender: "Nữ",
      birthday: "2001-02-10",
      email: "huongtran@staff.myhome.com",
      phone: "0911223344",
      city: "Hà Nội",
      district: "Hoàng Mai",
      subdistrict: "Lĩnh Nam",
      address: "Số 456, Ngõ 78, Lĩnh Nam, Hoàng Mai, Hà Nội",
      ApartmentId: 17,
      account: false,
      joinDate: "2017-01-01",
      leaveDate: null,
    },
    {
      firstName: "Dương",
      lastName: "Nguyễn",
      gender: "Nam",
      birthday: "1996-05-15",
      email: "duongnguyen@resident.myhome.com",
      phone: "0966888999",
      city: "Hồ Chí Minh",
      district: "Quận 4",
      subdistrict: "Phường 7",
      address: "Số 123, Ngõ 45, Phường 7, Quận 4, Hồ Chí Minh",
      ApartmentId: null,
      account: true,
      joinDate: "2019-01-10",
      leaveDate: "2021-01-10",
    },
    {
      firstName: "Hương",
      lastName: "Trần",
      gender: "Nữ",
      birthday: "2001-02-10",
      email: "huongtran@staff.myhome.com",
      phone: "0911223344",
      city: "Hà Nội",
      district: "Hoàng Mai",
      subdistrict: "Lĩnh Nam",
      address: "Số 456, Ngõ 78, Lĩnh Nam, Hoàng Mai, Hà Nội",
      ApartmentId: 17,
      account: false,
      joinDate: "2018-02-20",
      leaveDate: null,
    },
    {
      firstName: "Việt",
      lastName: "Phạm",
      gender: "Nam",
      birthday: "2003-11-12",
      email: "vietpham@admin.myhome.com",
      phone: "0912345678",
      city: "Đà Nẵng",
      district: "Quận Liên Chiểu",
      subdistrict: "Phường Thanh Khê Đông",
      address:
        "Số 789, Ngõ 90, Phường Thanh Khê Đông, Quận Liên Chiểu, Đà Nẵng",
      ApartmentId: 18,
      account: true,
      joinDate: "2017-05-25",
      leaveDate: null,
    },
    {
      firstName: "Hà",
      lastName: "Lê",
      gender: "Nữ",
      birthday: "1997-06-05",
      email: "hale@resident.myhome.com",
      phone: "0987654321",
      city: "Hồ Chí Minh",
      district: "Quận 1",
      subdistrict: "Bến Thành",
      address: "Số 123, Ngõ 45, Bến Thành, Quận 1, Hồ Chí Minh",
      ApartmentId: 19,
      account: true,
      joinDate: "2016-07-15",
      leaveDate: null,
    },
    {
      firstName: "Khải",
      lastName: "Ngô",
      gender: "Nam",
      birthday: "2002-01-20",
      email: "khai.ngo@staff.myhome.com",
      phone: "0978123456",
      city: "Hà Nội",
      district: "Ba Đình",
      subdistrict: "Trúc Bạch",
      address: "Số 456, Ngõ 78, Trúc Bạch, Ba Đình, Hà Nội",
      ApartmentId: null,
      account: false,
      joinDate: "2019-10-01",
      leaveDate: "2021-10-01",
    },
    {
      firstName: "Nam",
      lastName: "Trần",
      gender: "Nam",
      birthday: "2001-04-22",
      email: "namtran@resident.myhome.com",
      phone: "0978123456",
      city: "Hồ Chí Minh",
      district: "Quận 1",
      subdistrict: "Bến Thành",
      address: "Số 456, Ngõ 78, Bến Thành, Quận 1, Hồ Chí Minh",
      ApartmentId: 8,
      account: true,
      joinDate: "2022-03-05",
      leaveDate: null,
    },
    {
      firstName: "Ngọc",
      lastName: "Nguyễn",
      gender: "Nữ",
      birthday: "1995-08-15",
      email: "ngoc.nguyen@resident.myhome.com",
      phone: "0912345678",
      city: "Hà Nội",
      district: "Ba Đình",
      subdistrict: "Quán Thánh",
      address: "Số 123, Ngách 45, Ngõ 67, Quán Thánh, Ba Đình, Hà Nội",
      ApartmentId: 1,
      account: true,
      joinDate: "2016-01-10",
      leaveDate: null,
    },
    {
      firstName: "Trung",
      lastName: "Phạm",
      gender: "Nam",
      birthday: "1992-05-20",
      email: "trung.pham@staff.myhome.com",
      phone: "0987654321",
      city: "Đà Nẵng",
      district: "Hải Châu",
      subdistrict: "Thạch Thang",
      address: "Số 456, Ngõ 78, Thạch Thang, Hải Châu, Đà Nẵng",
      ApartmentId: 2,
      account: true,
      joinDate: "2013-12-05",
      leaveDate: null,
    },
    {
      firstName: "Lan",
      lastName: "Trần",
      gender: "Nữ",
      birthday: "2000-11-10",
      email: "lan.tran@admin.myhome.com",
      phone: "0978123456",
      city: "Hồ Chí Minh",
      district: "Quận 5",
      subdistrict: "Phường 10",
      address: "Số 789, Ngõ 90, Phường 10, Quận 5, Hồ Chí Minh",
      ApartmentId: 3,
      account: false,
      joinDate: "2012-08-30",
      leaveDate: null,
    },
    {
      firstName: "Nam",
      lastName: "Ngô",
      gender: "Nam",
      birthday: "1998-07-08",
      email: "nam.ngo@resident.myhome.com",
      phone: "0922334455",
      city: "Hà Nội",
      district: "Hoàng Mai",
      subdistrict: "Mai Động",
      address: "Số 234, Ngõ 56, Mai Động, Hoàng Mai, Hà Nội",
      ApartmentId: 4,
      account: true,
      joinDate: "2015-05-15",
      leaveDate: null,
    },
    {
      firstName: "Thu",
      lastName: "Trần",
      gender: "Nữ",
      birthday: "1993-12-25",
      email: "thu.tran@staff.myhome.com",
      phone: "0966888999",
      city: "Hồ Chí Minh",
      district: "Quận 7",
      subdistrict: "Phường Tân Phong",
      address: "Số 567, Ngõ 78, Phường Tân Phong, Quận 7, Hồ Chí Minh",
      ApartmentId: 5,
      account: true,
      joinDate: "2018-02-10",
      leaveDate: null,
    },
    {
      firstName: "Quang",
      lastName: "Lê",
      gender: "Nam",
      birthday: "2002-02-18",
      email: "quang.le@admin.myhome.com",
      phone: "0911223344",
      city: "Đà Nẵng",
      district: "Quận Liên Chiểu",
      subdistrict: "Phường Thanh Khê Đông",
      address:
        "Số 789, Ngõ 90, Phường Thanh Khê Đông, Quận Liên Chiểu, Đà Nẵng",
      ApartmentId: 6,
      account: false,
      joinDate: "2014-03-05",
      leaveDate: null,
    },
    {
      firstName: "Hạnh",
      lastName: "Nguyễn",
      gender: "Nữ",
      birthday: "1999-08-30",
      email: "hanh.nguyen@resident.myhome.com",
      phone: "0987654321",
      city: "Hà Nội",
      district: "Hai Bà Trưng",
      subdistrict: "Lê Đại Hành",
      address: "Số 123, Ngõ 45, Lê Đại Hành, Hai Bà Trưng, Hà Nội",
      ApartmentId: 7,
      account: true,
      joinDate: "2019-01-20",
      leaveDate: null,
    },
    {
      firstName: "Đức",
      lastName: "Phạm",
      gender: "Nam",
      birthday: "2001-04-22",
      email: "duc.pham@staff.myhome.com",
      phone: "0978123456",
      city: "Hồ Chí Minh",
      district: "Quận 1",
      subdistrict: "Bến Thành",
      address: "Số 456, Ngõ 78, Bến Thành, Quận 1, Hồ Chí Minh",
      ApartmentId: 8,
      account: true,
      joinDate: "2015-11-12",
      leaveDate: null,
    },
    {
      firstName: "Linh",
      lastName: "Vũ",
      gender: "Nữ",
      birthday: "2006-11-12",
      email: "linh.vu@admin.myhome.com",
      phone: "0922334455",
      city: "Đà Nẵng",
      district: "Quận Sơn Trà",
      subdistrict: "Phường Mân Thái",
      address: "Số 789, Ngõ 90, Phường Mân Thái, Quận Sơn Trà, Đà Nẵng",
      ApartmentId: null,
      account: false,
      joinDate: "2013-07-01",
      leaveDate: "2016-07-01",
    },
    {
      firstName: "Minh",
      lastName: "Nguyễn",
      gender: "Nam",
      birthday: "1997-06-05",
      email: "minh.nguyen@resident.myhome.com",
      phone: "0966888999",
      city: "Hồ Chí Minh",
      district: "Quận 2",
      subdistrict: "Thảo Điền",
      address: "Số 123, Ngõ 45, Thảo Điền, Quận 2, Hồ Chí Minh",
      ApartmentId: null,
      account: true,
      joinDate: "2017-10-20",
      leaveDate: "2020-10-20",
    },
    {
      firstName: "Hà",
      lastName: "Trần",
      gender: "Nữ",
      birthday: "2000-01-20",
      email: "ha.tran@staff.myhome.com",
      phone: "0911223344",
      city: "Hà Nội",
      district: "Ba Đình",
      subdistrict: "Trúc Bạch",
      address: "Số 456, Ngõ 78, Trúc Bạch, Ba Đình, Hà Nội",
      ApartmentId: null,
      account: false,
      joinDate: "2015-04-01",
      leaveDate: "2019-04-01",
    },
    {
      firstName: "Thành",
      lastName: "Lê",
      gender: "Nam",
      birthday: "1998-03-18",
      email: "thanh.le@admin.myhome.com",
      phone: "0912345678",
      city: "Đà Nẵng",
      district: "Quận Hải Châu",
      subdistrict: "Phường Nam Dương",
      address: "Số 789, Ngõ 90, Phường Nam Dương, Quận Hải Châu, Đà Nẵng",
      ApartmentId: 12,
      account: true,
      joinDate: "2018-08-15",
      leaveDate: null,
    },
    {
      firstName: "Trang",
      lastName: "Ngô",
      gender: "Nữ",
      birthday: "2005-09-10",
      email: "trang.ngo@resident.myhome.com",
      phone: "0987654321",
      city: "Hồ Chí Minh",
      district: "Quận 3",
      subdistrict: "Phường 6",
      address: "Số 123, Ngõ 45, Phường 6, Quận 3, Hồ Chí Minh",
      ApartmentId: 13,
      account: true,
      joinDate: "2018-08-15",
      leaveDate: null,
    },
    {
      firstName: "Ngọc",
      lastName: "Trần",
      gender: "Nam",
      birthday: "1995-08-20",
      email: "ngoc.tran@resident.myhome.com",
      phone: "0987654321",
      city: "Hà Nội",
      district: "Ba Đình",
      subdistrict: "Quán Thánh",
      address: "Số 123, Ngách 45, Ngõ 67, Quán Thánh, Ba Đình, Hà Nội",
      ApartmentId: 1,
      account: true,
      joinDate: "2016-01-15",
      leaveDate: null,
    },
    {
      firstName: "Thu",
      lastName: "Nguyễn",
      gender: "Nữ",
      birthday: "1990-03-10",
      email: "thu.nguyen@resident.myhome.com",
      phone: "0912345678",
      city: "Hồ Chí Minh",
      district: "Quận 1",
      subdistrict: "Bến Thành",
      address: "Số 456, Ngõ 78, Bến Thành, Quận 1, Hồ Chí Minh",
      ApartmentId: 2,
      account: true,
      joinDate: "2013-07-22",
      leaveDate: null,
    },
    {
      firstName: "Linh",
      lastName: "Phạm",
      gender: "Nam",
      birthday: "1992-11-18",
      email: "linh.pham@staff.myhome.com",
      phone: "0922334455",
      city: "Đà Nẵng",
      district: "Quận Hải Châu",
      subdistrict: "Phường Nam Dương",
      address: "Số 789, Ngõ 90, Phường Nam Dương, Quận Hải Châu, Đà Nẵng",
      ApartmentId: 3,
      account: true,
      joinDate: "2014-05-05",
      leaveDate: null,
    },
    {
      firstName: "Hải",
      lastName: "Ngô",
      gender: "Nam",
      birthday: "1997-06-05",
      email: "hai.ngo@resident.myhome.com",
      phone: "0966888999",
      city: "Hồ Chí Minh",
      district: "Quận 7",
      subdistrict: "Phường Tân Phong",
      address: "Số 567, Ngõ 78, Phường Tân Phong, Quận 7, Hồ Chí Minh",
      ApartmentId: 4,
      account: true,
      joinDate: "2015-12-25",
      leaveDate: null,
    },
    {
      firstName: "Mai",
      lastName: "Trần",
      gender: "Nữ",
      birthday: "2000-01-30",
      email: "mai.tran@admin.myhome.com",
      phone: "0911223344",
      city: "Hà Nội",
      district: "Hai Bà Trưng",
      subdistrict: "Lê Đại Hành",
      address: "Số 123, Ngõ 45, Lê Đại Hành, Hai Bà Trưng, Hà Nội",
      ApartmentId: null,
      account: false,
      joinDate: "2018-03-18",
      leaveDate: "2021-03-18",
    },
    {
      firstName: "Quân",
      lastName: "Lê",
      gender: "Nam",
      birthday: "1993-02-28",
      email: "quan.le@admin.myhome.com",
      phone: "0987654321",
      city: "Đà Nẵng",
      district: "Quận Sơn Trà",
      subdistrict: "Phường Mân Thái",
      address: "Số 456, Ngõ 78, Phường Mân Thái, Quận Sơn Trà, Đà Nẵng",
      ApartmentId: 6,
      account: true,
      joinDate: "2017-08-30",
      leaveDate: null,
    },
    {
      firstName: "Hồng",
      lastName: "Nguyễn",
      gender: "Nữ",
      birthday: "1995-09-12",
      email: "hong.nguyen@resident.myhome.com",
      phone: "0978123456",
      city: "Hồ Chí Minh",
      district: "Quận 2",
      subdistrict: "Thảo Điền",
      address: "Số 123, Ngõ 45, Thảo Điền, Quận 2, Hồ Chí Minh",
      ApartmentId: 7,
      account: true,
      joinDate: "2016-12-15",
      leaveDate: null,
    },
    {
      firstName: "Thảo",
      lastName: "Phạm",
      gender: "Nữ",
      birthday: "1998-07-05",
      email: "thao.pham@staff.myhome.com",
      phone: "0922334455",
      city: "Đà Nẵng",
      district: "Quận Liên Chiểu",
      subdistrict: "Phường Thanh Khê Đông",
      address:
        "Số 789, Ngõ 90, Phường Thanh Khê Đông, Quận Liên Chiểu, Đà Nẵng",
      ApartmentId: null,
      account: false,
      joinDate: "2019-06-10",
      leaveDate: "2022-06-10",
    },
    {
      firstName: "Anh",
      lastName: "Lê",
      gender: "Nam",
      birthday: "2002-11-12",
      email: "anh.le@resident.myhome.com",
      phone: "0966888999",
      city: "Hồ Chí Minh",
      district: "Quận 4",
      subdistrict: "Phường 7",
      address: "Số 123, Ngõ 45, Phường 7, Quận 4, Hồ Chí Minh",
      ApartmentId: 9,
      account: true,
      joinDate: "2018-02-10",
      leaveDate: null,
    },
    {
      firstName: "Hà",
      lastName: "Trần",
      gender: "Nữ",
      birthday: "1996-05-15",
      email: "ha.tran@admin.myhome.com",
      phone: "0912345678",
      city: "Hà Nội",
      district: "Hoàn Kiếm",
      subdistrict: "Phan Chu Trinh",
      address: "Số 456, Ngõ 78, Phan Chu Trinh, Hoàn Kiếm, Hà Nội",
      ApartmentId: 10,
      account: true,
      joinDate: "2015-10-22",
      leaveDate: null,
    },
    {
      firstName: "Nghĩa",
      lastName: "Nguyễn",
      gender: "Nam",
      birthday: "1999-08-30",
      email: "nghia.nguyen@staff.myhome.com",
      phone: "0987654321",
      city: "Đà Nẵng",
      district: "Quận Sơn Trà",
      subdistrict: "Phường Thọ Quang",
      address: "Số 123, Ngõ 45, Phường Thọ Quang, Quận Sơn Trà, Đà Nẵng",
      ApartmentId: null,
      account: false,
      joinDate: "2016-01-20",
      leaveDate: "2019-01-20",
    },
    {
      firstName: "Duy",
      lastName: "Phạm",
      gender: "Nam",
      birthday: "2004-04-22",
      email: "duy.pham@resident.myhome.com",
      phone: "0978123456",
      city: "Hồ Chí Minh",
      district: "Quận 3",
      subdistrict: "Phường 6",
      address: "Số 456, Ngõ 78, Phường 6, Quận 3, Hồ Chí Minh",
      ApartmentId: 12,
      account: true,
      joinDate: "2013-12-25",
      leaveDate: null,
    },
    {
      firstName: "Hồng",
      lastName: "Lê",
      gender: "Nữ",
      birthday: "1997-06-05",
      email: "hong.le@staff.myhome.com",
      phone: "0922334455",
      city: "Đà Nẵng",
      district: "Quận Liên Chiểu",
      subdistrict: "Phường Thanh Khê Đông",
      address: "Số 789, Ngõ 90, Phường Thanh Khê Đông, Quận Long Biên",
      ApartmentId: 13,
      account: true,
      joinDate: "2013-12-25",
      leaveDate: null,
    },

    {
      firstName: "Thảo",
      lastName: "Ngô",
      gender: "Nữ",
      birthday: "2002-01-20",
      email: "thao.ngo@admin.myhome.com",
      phone: "0978123456",
      city: "Hà Nội",
      district: "Ba Đình",
      subdistrict: "Trúc Bạch",
      address: "Số 456, Ngõ 78, Trúc Bạch, Ba Đình, Hà Nội",
      ApartmentId: null,
      account: false,
      joinDate: "2017-04-15",
      leaveDate: "2020-04-15",
    },
    {
      firstName: "Tuấn",
      lastName: "Phạm",
      gender: "Nam",
      birthday: "2003-08-10",
      email: "tuan.pham@resident.myhome.com",
      phone: "0922334455",
      city: "Hồ Chí Minh",
      district: "Quận 1",
      subdistrict: "Bến Thành",
      address: "Số 123, Ngõ 45, Bến Thành, Quận 1, Hồ Chí Minh",
      ApartmentId: 14,
      account: true,
      joinDate: "2015-05-28",
      leaveDate: null,
    },
    {
      firstName: "Yến",
      lastName: "Lê",
      gender: "Nữ",
      birthday: "1999-02-18",
      email: "yen.le@admin.myhome.com",
      phone: "0911223344",
      city: "Hà Nội",
      district: "Hoàng Mai",
      subdistrict: "Lĩnh Nam",
      address: "Số 456, Ngõ 78, Lĩnh Nam, Hoàng Mai, Hà Nội",
      ApartmentId: 15,
      account: false,
      joinDate: "2017-12-30",
      leaveDate: null,
    },
    {
      firstName: "Dũng",
      lastName: "Nguyễn",
      gender: "Nam",
      birthday: "1996-05-15",
      email: "dung.nguyen@staff.myhome.com",
      phone: "0966888999",
      city: "Hồ Chí Minh",
      district: "Quận 4",
      subdistrict: "Phường 7",
      address: "Số 123, Ngõ 45, Phường 7, Quận 4, Hồ Chí Minh",
      ApartmentId: 16,
      account: true,
      joinDate: "2015-02-25",
      leaveDate: null,
    },
    {
      firstName: "Hương",
      lastName: "Trần",
      gender: "Nữ",
      birthday: "2001-02-10",
      email: "huong.tran@admin.myhome.com",
      phone: "0911223344",
      city: "Hà Nội",
      district: "Ba Đình",
      subdistrict: "Trúc Bạch",
      address: "Số 456, Ngõ 78, Trúc Bạch, Ba Đình, Hà Nội",
      ApartmentId: 17,
      account: false,
      joinDate: "2019-01-15",
      leaveDate: null,
    },
    {
      firstName: "Việt",
      lastName: "Phạm",
      gender: "Nam",
      birthday: "2003-11-12",
      email: "viet.pham@resident.myhome.com",
      phone: "0912345678",
      city: "Đà Nẵng",
      district: "Quận Liên Chiểu",
      subdistrict: "Phường Thanh Khê Đông",
      address:
        "Số 789, Ngõ 90, Phường Thanh Khê Đông, Quận Liên Chiểu, Đà Nẵng",
      ApartmentId: 18,
      account: true,
      joinDate: "2016-10-18",
      leaveDate: null,
    },
    {
      firstName: "Hà",
      lastName: "Lê",
      gender: "Nữ",
      birthday: "1997-06-05",
      email: "ha.le@resident.myhome.com",
      phone: "0987654321",
      city: "Hồ Chí Minh",
      district: "Quận 1",
      subdistrict: "Bến Thành",
      address: "Số 123, Ngõ 45, Bến Thành, Quận 1, Hồ Chí Minh",
      ApartmentId: 19,
      account: true,
      joinDate: "2015-08-12",
      leaveDate: null,
    },
    {
      firstName: "Khải",
      lastName: "Ngô",
      gender: "Nam",
      birthday: "2002-01-20",
      email: "khai.ngo@staff.myhome.com",
      phone: "0978123456",
      city: "Hà Nội",
      district: "Ba Đình",
      subdistrict: "Trúc Bạch",
      address: "Số 456, Ngõ 78, Trúc Bạch, Ba Đình, Hà Nội",
      ApartmentId: null,
      account: false,
      joinDate: "2018-07-05",
      leaveDate: "2021-07-05",
    },
    {
      firstName: "Trang",
      lastName: "Nguyễn",
      gender: "Nữ",
      birthday: "1995-03-18",
      email: "trang.nguyen@resident.myhome.com",
      phone: "0966888999",
      city: "Hồ Chí Minh",
      district: "Quận 3",
      subdistrict: "Phường 6",
      address: "Số 123, Ngõ 45, Phường 6, Quận 3, Hồ Chí Minh",
      ApartmentId: 1,
      account: true,
      joinDate: "2016-05-10",
      leaveDate: null,
    },
    {
      firstName: "Tuấn",
      lastName: "Phạm",
      gender: "Nam",
      birthday: "1994-12-25",
      email: "tuan.pham@staff.myhome.com",
      phone: "0978123456",
      city: "Hà Nội",
      district: "Hoàn Kiếm",
      subdistrict: "Phan Chu Trinh",
      address: "Số 456, Ngõ 78, Phan Chu Trinh, Hoàn Kiếm, Hà Nội",
      ApartmentId: 2,
      account: false,
      joinDate: "2013-08-28",
      leaveDate: null,
    },
    {
      firstName: "Yến",
      lastName: "Lê",
      gender: "Nữ",
      birthday: "1999-08-30",
      email: "yen.le@admin.myhome.com",
      phone: "0922334455",
      city: "Đà Nẵng",
      district: "Quận Sơn Trà",
      subdistrict: "Phường Thọ Quang",
      address: "Số 789, Ngõ 90, Phường Thọ Quang, Quận Sơn Trà, Đà Nẵng",
      ApartmentId: 3,
      account: true,
      joinDate: "2014-07-15",
      leaveDate: null,
    },
    {
      firstName: "Dũng",
      lastName: "Nguyễn",
      gender: "Nam",
      birthday: "1996-05-15",
      email: "dung.nguyen@resident.myhome.com",
      phone: "0966888999",
      city: "Hồ Chí Minh",
      district: "Quận 4",
      subdistrict: "Phường 7",
      address: "Số 123, Ngõ 45, Phường 7, Quận 4, Hồ Chí Minh",
      ApartmentId: 4,
      account: true,
      joinDate: "2015-02-25",
      leaveDate: null,
    },
    {
      firstName: "Hương",
      lastName: "Trần",
      gender: "Nữ",
      birthday: "2001-02-10",
      email: "huong.tran@admin.myhome.com",
      phone: "0911223344",
      city: "Hà Nội",
      district: "Ba Đình",
      subdistrict: "Trúc Bạch",
      address: "Số 456, Ngõ 78, Trúc Bạch, Ba Đình, Hà Nội",
      ApartmentId: 5,
      account: false,
      joinDate: "2019-01-15",
      leaveDate: null,
    },
    {
      firstName: "Việt",
      lastName: "Phạm",
      gender: "Nam",
      birthday: "2003-11-12",
      email: "viet.pham@resident.myhome.com",
      phone: "0912345678",
      city: "Đà Nẵng",
      district: "Quận Liên Chiểu",
      subdistrict: "Phường Thanh Khê Đông",
      address:
        "Số 789, Ngõ 90, Phường Thanh Khê Đông, Quận Liên Chiểu, Đà Nẵng",
      ApartmentId: 6,
      account: true,
      joinDate: "2016-10-18",
      leaveDate: null,
    },
    {
      firstName: "Hà",
      lastName: "Lê",
      gender: "Nữ",
      birthday: "1997-06-05",
      email: "ha.le@resident.myhome.com",
      phone: "0987654321",
      city: "Hồ Chí Minh",
      district: "Quận 1",
      subdistrict: "Bến Thành",
      address: "Số 123, Ngõ 45, Bến Thành, Quận 1, Hồ Chí Minh",
      ApartmentId: 7,
      account: true,
      joinDate: "2017-04-20",
      leaveDate: null,
    },
    {
      firstName: "Khải",
      lastName: "Nguyễn",
      gender: "Nam",
      birthday: "2002-01-20",
      email: "khai.nguyen@staff.myhome.com",
      phone: "0978123456",
      city: "Hà Nội",
      district: "Ba Đình",
      subdistrict: "Trúc Bạch",
      address: "Số 456, Ngõ 78, Trúc Bạch, Ba Đình, Hà Nội",
      ApartmentId: null,
      account: false,
      joinDate: "2018-07-05",
      leaveDate: "2021-07-05",
    },
    {
      firstName: "Linh",
      lastName: "Vũ",
      gender: "Nữ",
      birthday: "2006-11-12",
      email: "linh.vu@admin.myhome.com",
      phone: "0922334455",
      city: "Đà Nẵng",
      district: "Quận Sơn Trà",
      subdistrict: "Phường Mân Thái",
      address: "Số 789, Ngõ 90, Phường Mân Thái, Quận Sơn Trà, Đà Nẵng",
      ApartmentId: 9,
      account: false,
      joinDate: "2020-05-22",
      leaveDate: null,
    },
    {
      firstName: "Minh",
      lastName: "Nguyễn",
      gender: "Nam",
      birthday: "1997-06-05",
      email: "minh.nguyen@resident.myhome.com",
      phone: "0966888999",
      city: "Hồ Chí Minh",
      district: "Quận 2",
      subdistrict: "Thảo Điền",
      address: "Số 123, Ngõ 45, Thảo Điền, Quận 2, Hồ Chí Minh",
      ApartmentId: 10,
      account: true,
      joinDate: "2015-08-12",
      leaveDate: null,
    },
    {
      firstName: "Huy",
      lastName: "Nguyễn",
      gender: "Nam",
      birthday: "1998-09-20",
      email: "huy.nguyen@resident.myhome.com",
      phone: "0911223344",
      city: "Hà Nội",
      district: "Cầu Giấy",
      subdistrict: "Quan Hoa",
      address: "Số 456, Ngõ 78, Quan Hoa, Cầu Giấy, Hà Nội",
      ApartmentId: null,
      account: true,
      joinDate: "2017-11-10",
      leaveDate: "2023-01-23",
    },
    {
      firstName: "Hạnh",
      lastName: "Lê",
      gender: "Nữ",
      birthday: "2000-05-15",
      email: "hanh.le@admin.myhome.com",
      phone: "0987654321",
      city: "Hồ Chí Minh",
      district: "Quận 1",
      subdistrict: "Bến Thành",
      address: "Số 123, Ngõ 45, Bến Thành, Quận 1, Hồ Chí Minh",
      ApartmentId: 12,
      account: false,
      joinDate: "2019-03-25",
      leaveDate: null,
    },
    {
      firstName: "Việt",
      lastName: "Trần",
      gender: "Nam",
      birthday: "2001-11-12",
      email: "viet.tran@staff.myhome.com",
      phone: "0912345678",
      city: "Đà Nẵng",
      district: "Quận Hải Châu",
      subdistrict: "Phường Hòa Thọ Đông",
      address: "Số 789, Ngõ 90, Phường Hòa Thọ Đông, Quận Hải Châu, Đà Nẵng",
      ApartmentId: 13,
      account: true,
      joinDate: "2018-08-18",
      leaveDate: null,
    },
    {
      firstName: "Hương",
      lastName: "Ngô",
      gender: "Nữ",
      birthday: "2002-02-10",
      email: "huong.ngo@resident.myhome.com",
      phone: "0978123456",
      city: "Hà Nội",
      district: "Hai Bà Trưng",
      subdistrict: "Thịnh Liệt",
      address: "Số 456, Ngõ 78, Thịnh Liệt, Hai Bà Trưng, Hà Nội",
      ApartmentId: null,
      account: false,
      joinDate: "2016-09-30",
      leaveDate: "2019-09-30",
    },
    {
      firstName: "Trang",
      lastName: "Phạm",
      gender: "Nữ",
      birthday: "1997-06-05",
      email: "trang.pham@admin.myhome.com",
      phone: "0966888999",
      city: "Hồ Chí Minh",
      district: "Quận 7",
      subdistrict: "Phường Tân Phong",
      address: "Số 123, Ngõ 45, Phường Tân Phong, Quận 7, Hồ Chí Minh",
      ApartmentId: 15,
      account: true,
      joinDate: "2014-12-15",
      leaveDate: null,
    },
    {
      firstName: "Tuấn",
      lastName: "Nguyễn",
      gender: "Nam",
      birthday: "1998-08-30",
      email: "tuan.nguyen@staff.myhome.com",
      phone: "0922334455",
      city: "Đà Nẵng",
      district: "Quận Liên Chiểu",
      subdistrict: "Phường Thanh Khê Đông",
      address:
        "Số 789, Ngõ 90, Phường Thanh Khê Đông, Quận Liên Chiểu, Đà Nẵng",
      ApartmentId: null,
      account: false,
      joinDate: "2015-06-20",
      leaveDate: "2018-06-20",
    },
    {
      firstName: "Yến",
      lastName: "Lê",
      gender: "Nữ",
      birthday: "1999-03-18",
      email: "yen.le@resident.myhome.com",
      phone: "0911223344",
      city: "Hà Nội",
      district: "Hoàng Mai",
      subdistrict: "Thanh Trì",
      address: "Số 456, Ngõ 78, Thanh Trì, Hoàng Mai, Hà Nội",
      ApartmentId: 17,
      account: true,
      joinDate: "2017-04-10",
      leaveDate: null,
    },
    {
      firstName: "Dũng",
      lastName: "Trần",
      gender: "Nam",
      birthday: "2000-12-25",
      email: "dung.tran@admin.myhome.com",
      phone: "0987654321",
      city: "Hồ Chí Minh",
      district: "Quận 4",
      subdistrict: "Phường 7",
      address: "Số 123, Ngõ 45, Phường 7, Quận 4, Hồ Chí Minh",
      ApartmentId: 18,
      account: false,
      joinDate: "2016-05-30",
      leaveDate: null,
    },
    {
      firstName: "Hương",
      lastName: "Nguyễn",
      gender: "Nữ",
      birthday: "1997-11-12",
      email: "huong.nguyen@staff.myhome.com",
      phone: "0978123456",
      city: "Đà Nẵng",
      district: "Quận Sơn Trà",
      subdistrict: "Phường Thọ Quang",
      address: "Số 789, Ngõ 90, Phường Thọ Quang, Quận Sơn Trà, Đà Nẵng",
      ApartmentId: 19,
      account: true,
      joinDate: "2019-09-10",
      leaveDate: null,
    },
    {
      firstName: "Lâm",
      lastName: "Phạm",
      gender: "Nam",
      birthday: "2002-06-05",
      email: "lam.pham@resident.myhome.com",
      phone: "0922334455",
      city: "Hà Nội",
      district: "Ba Đình",
      subdistrict: "Trúc Bạch",
      address: "Số 456, Ngõ 78, Trúc Bạch, Ba Đình, Hà Nội",
      ApartmentId: 20,
      account: false,
      joinDate: "2018-12-20",
      leaveDate: null,
    },
    {
      firstName: "Mai",
      lastName: "Nguyễn",
      gender: "Nữ",
      birthday: "2003-08-30",
      email: "mai.nguyen@staff.myhome.com",
      phone: "0911223344",
      city: "Hà Nội",
      district: "Hoàn Kiếm",
      subdistrict: "Phan Chu Trinh",
      address: "Số 123, Ngõ 45, Phan Chu Trinh, Hoàn Kiếm, Hà Nội",
      ApartmentId: 6,
      account: true,
      joinDate: "2018-09-10",
      leaveDate: null,
    },
    {
      firstName: "Thiên",
      lastName: "Phạm",
      gender: "Nam",
      birthday: "2004-02-10",
      email: "thien.pham@resident.myhome.com",
      phone: "0987654321",
      city: "Hồ Chí Minh",
      district: "Quận 1",
      subdistrict: "Bến Thành",
      address: "Số 456, Ngõ 78, Bến Thành, Quận 1, Hồ Chí Minh",
      ApartmentId: null,
      account: false,
      joinDate: "2016-07-05",
      leaveDate: "2018-09-10",
    },
    {
      firstName: "Nga",
      lastName: "Lê",
      gender: "Nữ",
      birthday: "2001-12-25",
      email: "nga.le@admin.myhome.com",
      phone: "0978123456",
      city: "Đà Nẵng",
      district: "Quận Hải Châu",
      subdistrict: "Phường Nam Dương",
      address: "Số 789, Ngõ 90, Phường Nam Dương, Quận Hải Châu, Đà Nẵng",
      ApartmentId: null,
      account: true,
      joinDate: "2019-03-18",
      leaveDate: "2022-10-13",
    },
    {
      firstName: "Phong",
      lastName: "Ngô",
      gender: "Nam",
      birthday: "1996-06-05",
      email: "phong.ngo@staff.myhome.com",
      phone: "0922334455",
      city: "Hồ Chí Minh",
      district: "Quận 4",
      subdistrict: "Phường 7",
      address: "Số 123, Ngõ 45, Phường 7, Quận 4, Hồ Chí Minh",
      ApartmentId: 8,
      account: false,
      joinDate: "2017-10-10",
      leaveDate: null,
    },
    {
      firstName: "Thu",
      lastName: "Vũ",
      gender: "Nữ",
      birthday: "2002-03-18",
      email: "thu.vu@resident.myhome.com",
      phone: "0966888999",
      city: "Hà Nội",
      district: "Ba Đình",
      subdistrict: "Trúc Bạch",
      address: "Số 456, Ngõ 78, Trúc Bạch, Ba Đình, Hà Nội",
      ApartmentId: 14,
      account: true,
      joinDate: "2018-08-30",
      leaveDate: null,
    },
    {
      firstName: "Tùng",
      lastName: "Phạm",
      gender: "Nam",
      birthday: "1997-11-12",
      email: "tung.pham@admin.myhome.com",
      phone: "0911223344",
      city: "Đà Nẵng",
      district: "Quận Liên Chiểu",
      subdistrict: "Phường Thanh Khê Đông",
      address:
        "Số 789, Ngõ 90, Phường Thanh Khê Đông, Quận Liên Chiểu, Đà Nẵng",
      ApartmentId: null,
      account: true,
      joinDate: "2015-05-15",
      leaveDate: "2022-09-13",
    },
    {
      firstName: "Dương",
      lastName: "Nguyễn",
      gender: "Nam",
      birthday: "1998-12-25",
      email: "duong.nguyen@staff.myhome.com",
      phone: "0987654321",
      city: "Hồ Chí Minh",
      district: "Quận 2",
      subdistrict: "Thảo Điền",
      address: "Số 123, Ngõ 45, Thảo Điền, Quận 2, Hồ Chí Minh",
      ApartmentId: 19,
      account: false,
      joinDate: "2016-06-05",
      leaveDate: null,
    },
    {
      firstName: "Hải",
      lastName: "Trần",
      gender: "Nam",
      birthday: "2001-01-20",
      email: "hai.tran@resident.myhome.com",
      phone: "0978123456",
      city: "Hà Nội",
      district: "Hoàng Mai",
      subdistrict: "Lĩnh Nam",
      address: "Số 456, Ngõ 78, Lĩnh Nam, Hoàng Mai, Hà Nội",
      ApartmentId: 2,
      account: true,
      joinDate: "2017-12-30",
      leaveDate: null,
    },
    {
      firstName: "Anh",
      lastName: "Lê",
      gender: "Nữ",
      birthday: "2000-06-05",
      email: "anh.le@staff.myhome.com",
      phone: "0922334455",
      city: "Đà Nẵng",
      district: "Quận Sơn Trà",
      subdistrict: "Phường Mân Thái",
      address: "Số 789, Ngõ 90, Phường Mân Thái, Quận Sơn Trà, Đà Nẵng",
      ApartmentId: 13,
      account: false,
      joinDate: "2019-09-10",
      leaveDate: null,
    },
    {
      firstName: "Thùy",
      lastName: "Nguyễn",
      gender: "Nữ",
      birthday: "2003-03-18",
      email: "thuy.nguyen@admin.myhome.com",
      phone: "0911223344",
      city: "Hồ Chí Minh",
      district: "Quận 1",
      subdistrict: "Bến Thành",
      address: "Số 123, Ngõ 45, Bến Thành, Quận 1, Hồ Chí Minh",
      ApartmentId: 8,
      account: true,
      joinDate: "2018-08-30",
      leaveDate: null,
    },
    {
      firstName: "Quỳnh",
      lastName: "Nguyễn",
      gender: "Nữ",
      birthday: "1999-05-15",
      email: "quynh.nguyen@admin.myhome.com",
      phone: "0911223344",
      city: "Hà Nội",
      district: "Hai Bà Trưng",
      subdistrict: "Thịnh Liệt",
      address: "Số 123, Ngõ 45, Thịnh Liệt, Hai Bà Trưng, Hà Nội",
      ApartmentId: 5,
      account: true,
      joinDate: "2017-10-10",
      leaveDate: null,
    },
    {
      firstName: "Vân",
      lastName: "Lê",
      gender: "Nữ",
      birthday: "2002-08-30",
      email: "van.le@staff.myhome.com",
      phone: "0987654321",
      city: "Hồ Chí Minh",
      district: "Quận 7",
      subdistrict: "Phường Tân Phong",
      address: "Số 456, Ngõ 78, Phường Tân Phong, Quận 7, Hồ Chí Minh",
      ApartmentId: 15,
      account: false,
      joinDate: "2018-03-25",
      leaveDate: null,
    },
    {
      firstName: "Duy",
      lastName: "Trần",
      gender: "Nam",
      birthday: "2000-11-12",
      email: "duy.tran@resident.myhome.com",
      phone: "0912345678",
      city: "Đà Nẵng",
      district: "Quận Liên Chiểu",
      subdistrict: "Phường Thanh Khê Đông",
      address:
        "Số 789, Ngõ 90, Phường Thanh Khê Đông, Quận Liên Chiểu, Đà Nẵng",
      ApartmentId: 10,
      account: true,
      joinDate: "2016-08-18",
      leaveDate: null,
    },
    {
      firstName: "Bích",
      lastName: "Ngô",
      gender: "Nữ",
      birthday: "1998-02-10",
      email: "bich.ngo@admin.myhome.com",
      phone: "0978123456",
      city: "Hà Nội",
      district: "Ba Đình",
      subdistrict: "Trúc Bạch",
      address: "Số 456, Ngõ 78, Trúc Bạch, Ba Đình, Hà Nội",
      ApartmentId: 3,
      account: false,
      joinDate: "2019-09-30",
      leaveDate: null,
    },
    {
      firstName: "Bình",
      lastName: "Phạm",
      gender: "Nam",
      birthday: "1997-06-05",
      email: "binh.pham@staff.myhome.com",
      phone: "0966888999",
      city: "Hồ Chí Minh",
      district: "Quận 4",
      subdistrict: "Phường 7",
      address: "Số 123, Ngõ 45, Phường 7, Quận 4, Hồ Chí Minh",
      ApartmentId: 18,
      account: true,
      joinDate: "2014-12-15",
      leaveDate: null,
    },
    {
      firstName: "Anh",
      lastName: "Nguyễn",
      gender: "Nam",
      birthday: "1998-08-30",
      email: "anh.nguyen@resident.myhome.com",
      phone: "0922334455",
      city: "Đà Nẵng",
      district: "Quận Sơn Trà",
      subdistrict: "Phường Thọ Quang",
      address: "Số 789, Ngõ 90, Phường Thọ Quang, Quận Sơn Trà, Đà Nẵng",
      ApartmentId: 12,
      account: false,
      joinDate: "2016-06-20",
      leaveDate: null,
    },
    {
      firstName: "Thùy",
      lastName: "Lê",
      gender: "Nữ",
      birthday: "2001-03-18",
      email: "thuy.le@admin.myhome.com",
      phone: "0911223344",
      city: "Hà Nội",
      district: "Hoàng Mai",
      subdistrict: "Thanh Trì",
      address: "Số 456, Ngõ 78, Thanh Trì, Hoàng Mai, Hà Nội",
      ApartmentId: 7,
      account: true,
      joinDate: "2015-07-05",
      leaveDate: null,
    },
    {
      firstName: "Hòa",
      lastName: "Nguyễn",
      gender: "Nam",
      birthday: "1999-12-25",
      email: "hoa.nguyen@staff.myhome.com",
      phone: "0987654321",
      city: "Hồ Chí Minh",
      district: "Quận 7",
      subdistrict: "Phường Tân Phong",
      address: "Số 123, Ngõ 45, Phường Tân Phong, Quận 7, Hồ Chí Minh",
      ApartmentId: 19,
      account: false,
      joinDate: "2017-09-10",
      leaveDate: null,
    },
    {
      firstName: "Trang",
      lastName: "Vũ",
      gender: "Nữ",
      birthday: "2002-06-05",
      email: "trang.vu@resident.myhome.com",
      phone: "0978123456",
      city: "Hà Nội",
      district: "Ba Đình",
      subdistrict: "Trúc Bạch",
      address: "Số 456, Ngõ 78, Trúc Bạch, Ba Đình, Hà Nội",
      ApartmentId: 2,
      account: true,
      joinDate: "2016-12-20",
      leaveDate: null,
    },
    {
      firstName: "Cường",
      lastName: "Phạm",
      gender: "Nam",
      birthday: "1997-11-12",
      email: "cuong.pham@admin.myhome.com",
      phone: "0922334455",
      city: "Đà Nẵng",
      district: "Quận Sơn Trà",
      subdistrict: "Phường Thọ Quang",
      address: "Số 789, Ngõ 90, Phường Thọ Quang, Quận Sơn Trà, Đà Nẵng",
      ApartmentId: null,
      account: false,
      joinDate: "2017-11-30",
      leaveDate: "2023-03-29",
    },
    {
      firstName: "Mai",
      lastName: "Nguyễn",
      gender: "Nữ",
      birthday: "2003-08-30",
      email: "mai.nguyen@staff.myhome.com",
      phone: "0911223344",
      city: "Hà Nội",
      district: "Hoàn Kiếm",
      subdistrict: "Phan Chu Trinh",
      address: "Số 123, Ngõ 45, Phan Chu Trinh, Hoàn Kiếm, Hà Nội",
      ApartmentId: 6,
      account: true,
      joinDate: "2018-09-10",
      leaveDate: null,
    },
    {
      firstName: "Thiên",
      lastName: "Phạm",
      gender: "Nam",
      birthday: "2004-02-10",
      email: "thien.pham@resident.myhome.com",
      phone: "0987654321",
      city: "Hồ Chí Minh",
      district: "Quận 1",
      subdistrict: "Bến Thành",
      address: "Số 456, Ngõ 78, Bến Thành, Quận 1, Hồ Chí Minh",
      ApartmentId: null,
      account: false,
      joinDate: "2016-07-05",
      leaveDate: "2018-09-10",
    },
    {
      firstName: "Nga",
      lastName: "Lê",
      gender: "Nữ",
      birthday: "2001-12-25",
      email: "nga.le@admin.myhome.com",
      phone: "0978123456",
      city: "Đà Nẵng",
      district: "Quận Hải Châu",
      subdistrict: "Phường Nam Dương",
      address: "Số 789, Ngõ 90, Phường Nam Dương, Quận Hải Châu, Đà Nẵng",
      ApartmentId: null,
      account: true,
      joinDate: "2019-03-18",
      leaveDate: "2022-10-13",
    },
    {
      firstName: "Phong",
      lastName: "Ngô",
      gender: "Nam",
      birthday: "1996-06-05",
      email: "phong.ngo@staff.myhome.com",
      phone: "0922334455",
      city: "Hồ Chí Minh",
      district: "Quận 4",
      subdistrict: "Phường 7",
      address: "Số 123, Ngõ 45, Phường 7, Quận 4, Hồ Chí Minh",
      ApartmentId: 8,
      account: false,
      joinDate: "2017-10-10",
      leaveDate: null,
    },
    {
      firstName: "Thu",
      lastName: "Vũ",
      gender: "Nữ",
      birthday: "2002-03-18",
      email: "thu.vu@resident.myhome.com",
      phone: "0966888999",
      city: "Hà Nội",
      district: "Ba Đình",
      subdistrict: "Trúc Bạch",
      address: "Số 456, Ngõ 78, Trúc Bạch, Ba Đình, Hà Nội",
      ApartmentId: 14,
      account: true,
      joinDate: "2018-08-30",
      leaveDate: null,
    },
    {
      firstName: "Tùng",
      lastName: "Phạm",
      gender: "Nam",
      birthday: "1997-11-12",
      email: "tung.pham@admin.myhome.com",
      phone: "0911223344",
      city: "Đà Nẵng",
      district: "Quận Liên Chiểu",
      subdistrict: "Phường Thanh Khê Đông",
      address:
        "Số 789, Ngõ 90, Phường Thanh Khê Đông, Quận Liên Chiểu, Đà Nẵng",
      ApartmentId: null,
      account: true,
      joinDate: "2015-05-15",
      leaveDate: "2022-09-13",
    },
    {
      firstName: "Dương",
      lastName: "Nguyễn",
      gender: "Nam",
      birthday: "1998-12-25",
      email: "duong.nguyen@staff.myhome.com",
      phone: "0987654321",
      city: "Hồ Chí Minh",
      district: "Quận 2",
      subdistrict: "Thảo Điền",
      address: "Số 123, Ngõ 45, Thảo Điền, Quận 2, Hồ Chí Minh",
      ApartmentId: 19,
      account: false,
      joinDate: "2016-06-05",
      leaveDate: null,
    },
    {
      firstName: "Hải",
      lastName: "Trần",
      gender: "Nam",
      birthday: "2001-01-20",
      email: "hai.tran@resident.myhome.com",
      phone: "0978123456",
      city: "Hà Nội",
      district: "Hoàng Mai",
      subdistrict: "Lĩnh Nam",
      address: "Số 456, Ngõ 78, Lĩnh Nam, Hoàng Mai, Hà Nội",
      ApartmentId: 2,
      account: true,
      joinDate: "2017-12-30",
      leaveDate: null,
    },
    {
      firstName: "Anh",
      lastName: "Lê",
      gender: "Nữ",
      birthday: "2000-06-05",
      email: "anh.le@staff.myhome.com",
      phone: "0922334455",
      city: "Đà Nẵng",
      district: "Quận Sơn Trà",
      subdistrict: "Phường Mân Thái",
      address: "Số 789, Ngõ 90, Phường Mân Thái, Quận Sơn Trà, Đà Nẵng",
      ApartmentId: 13,
      account: false,
      joinDate: "2019-09-10",
      leaveDate: null,
    },
    {
      firstName: "Thùy",
      lastName: "Nguyễn",
      gender: "Nữ",
      birthday: "2003-03-18",
      email: "thuy.nguyen@admin.myhome.com",
      phone: "0911223344",
      city: "Hồ Chí Minh",
      district: "Quận 1",
      subdistrict: "Bến Thành",
      address: "Số 123, Ngõ 45, Bến Thành, Quận 1, Hồ Chí Minh",
      ApartmentId: 8,
      account: true,
      joinDate: "2018-08-30",
      leaveDate: null,
    },
  ];

  for (const userInfo of userInfos) {
    await UserInfoService.createUserInfoNew(userInfo);
  }
}
